---
- name: create rtail dirs
  file:
    path="{{ item|safe|trim }}"
    state=directory
    owner="{{ rtail_user }}"
    group="{{ rtail_group }}"
    mode=777
    recurse=yes
  changed_when: false
  with_items:
    - "{{ rtail_opt_dir }}"
    - "{{ rtail_config_dir }}"
    - "{{ rtail_tmp_dir }}"
    - "{{ rtail_data_dir }}"
  tags:
    - rtail
    - rtail-install
    - rtail-config-main
