---
- name: create rtail dirs
  file:
    path="{{ item|safe|trim }}"
    state=directory
    owner="{{ rtail_user }}"
    group="{{ rtail_group }}"
    mode=777
    recurse=yes
  changed_when: false
  with_items:
    - "{{ rtail_opt_dir }}"
    - "{{ rtail_config_dir }}"
    - "{{ rtail_tmp_dir }}"
    - "{{ rtail_data_dir }}"
  tags:
    - rtail
    - rtail-install
    - rtail-config-main

- name: transfer ssl crt (tajawal-sub-domain-chained.crt) configuration
  template: src={{ item }} dest={{ rtail_config_dir }}/{{ item | basename }} force=yes mode=755
  with_fileglob:
    - ./../ssl/*tajawal.io/*.crt
  tags:
    - rtail-ssl-certs
    - rtail-transfer-ssl-crt

- name: transfer ssl pem (tajawal-sub-domain-private-key.pem) configuration
  template: src={{ item }} dest={{ rtail_config_dir }}/{{ item | basename }} force=yes mode=755
  with_fileglob:
      - ./../ssl/*tajawal.io/*-key.pem
  tags:
    - rtail
    - rtail-transfer-ssl-pem
