---
- name: copy rtail docker-compose file
  template:
     dest="{{ rtail_opt_dir }}/docker-compose.yml"
     owner="{{ rtail_user }}"
     group="{{ rtail_group }}"
     mode=777
     src=docker-compose.yml
  tags:
    - rtail
    - rtail-install
    - rtail-docker-compose
    - rtail-config
    - rtail-config-main
