---
- name: copy jenkins docker-compose file
  template:
     dest="{{ jenkins_opt_dir }}/docker-compose.yml"
     owner="{{ jenkins_user }}"
     group="{{ jenkins_group }}"
     mode=777
     src=docker-compose.yml
  tags:
    - jenkins
    - jenkins-install
    - jenkins-docker-compose
    - jenkins-config
    - jenkins-config-main
