---
- name: users rtail
  include: users.yml
  tags:
    - rtail
    - rtail-install
    - rtail-config

- name: configure rtail
  include: configure.yml
  tags:
    - rtail
    - rtail-install
    - rtail-config

- name: install docker rtail
  include: install.yml
  tags:
    - rtail
    - rtail-install
    - rtail-docker-rtail

- name: start docker rtail
  include: started.yml
  tags:
    - rtail
    - rtail-install
    - rtail-docker-rtail

# Update rtail and install configured plugins.
#- include: plugins.yml
#  tags:
#    - rtail
#    - rtail-plugins
#    - rtail-docker-rtail

- include: keys.yml
  when: copy_rtail_key is defined
  tags:
    - rtail
    - rtail-plugins
    - rtail-keys
    - rtail-docker-rtail
