---
- name: users rtail
  include: users.yml
  tags:
    - rtail
    - rtail-install
    - rtail-config

- name: configure rtail
  include: configure.yml
  tags:
    - rtail
    - rtail-install
    - rtail-config

- name: install docker rtail
  include: install.yml
  tags:
    - rtail
    - rtail-install
    - rtail-docker-rtail

- name: start docker rtail
  include: started.yml
  tags:
    - rtail
    - rtail-install
    - rtail-docker-rtail
