---
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: wait for rtail to start up before proceeding.
  shell: "curl -D - --silent http://{{ rtail_hostname }}:{{ rtail_http_port }}{{ rtail_url_prefix }}/cli/"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "{{ rtail_connection_retries }}"
  delay: "{{ rtail_connection_delay }}"
  changed_when: false
  tags:
    - full-deploy

- name: get the rtail-cli jarfile from the rtail server.
  get_url:
    url: "http://{{ rtail_hostname }}:{{ rtail_http_port }}{{ rtail_url_prefix }}/jnlpJars/rtail-cli.jar"
    dest: "{{ rtail_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10
  tags:
    - full-deploy


- name: Update rtail plugin data.
  shell: >
    curl -L https://updates.rtail-ci.org/update-center.json | sed '1d;$d' > /var/lib/rtail/updates/default.json
    creates=/var/lib/rtail/updates/default.json
  tags:
    - rtail
    - rtail-plugin-update
    - rtail-default

- name: Permissions for default.json updates info.
  file:
    path: /var/lib/rtail/updates/default.json
    owner: rtail
    group: rtail
    mode: 0755
  tags:
    - permissions
    - rtail-permissions
    - rtail-plugin-update
    - rtail-default

- name: Install rtail plugins.
  with_items: "{{ rtail_plugins }}"
  become: yes
  get_url: dest="{{ rtail_home }}/plugins/{{ item | mandatory }}.jpi"
           url="https://updates.rtail-ci.org/latest/{{ item }}.hpi"
           owner=rtail group=rtail mode=0644 validate_certs=no
  notify: restart rtail
  tags:
    - rtail
    - rtail-setup-plugins
