---
- name: setup group
  group: name="{{ jenkins_group }}" system=no
  tags:
    - jenkins
    - jenkins-install
    - jenkins-user

- name: setup user
  user: name="{{ jenkins_user }}" system=no group="{{ jenkins_group }}"
  tags:
    - jenkins
    - jenkins-install
    - jenkins-user
