---
- name: start docker-compose-jenkins
  become: true
  docker_service:
    project_src: "{{ jenkins_opt_dir }}"
    state: present

- name: restart docker-compose-jenkins
  become: true
  docker_service:
    project_src: "{{ jenkins_opt_dir }}"
    state: present
    restarted: yes

- name: stop docker-compose-jenkins
  become: true
  docker_service:
    project_src: "{{ jenkins_opt_dir }}"
    state: absent
