version: '3.1'
services:
  rtail:
    image: anmolnagpal/docker-rtail
    container_name: rtail
    environment:
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 165536
        hard: 165536
    cap_add:
      - ALL
    ports:
      - {{ rtail_http_port }}:{{ rtail_http_port }}
      - {{ rtail_https_port }}:{{ rtail_https_port }}
      - {{ rtail_agent_port }}:{{ rtail_agent_port }}/udp
    network_mode: host
